services:
  web:
    container_name: filmdiary_web
#    image: ${DOCKER_HUB_USERNAME}/filmdiary:${DOCKER_HUB_TAG}
    build: .
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - ALLOWED_URLS=${ALLOWED_URLS}
    volumes:
      - fd_static_volume:/app/staticfiles
      - fd_web_media:/app/media
    expose:
      - "8000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - fd_static_volume:/app/staticfiles:ro
      - fd_web_media:/app/media:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${CERTIFICATE_DIR}:/serv/certs:ro
    depends_on:
      - web
  db:
    container_name: filmdiary_db
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - fd_postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:alpine
    expose:
      - '6379'
    restart: unless-stopped
    volumes:
      - fd_redis_data:/data
  celery:
    image: ${DOCKER_HUB_USERNAME}/filmdiary:${DOCKER_HUB_TAG}
    command: celery -A config worker -l INFO -P solo
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - ALLOWED_URLS=${ALLOWED_URLS}
    restart: unless-stopped
    depends_on:
      - redis
      - db
  celery-beat:
    image: ${DOCKER_HUB_USERNAME}/filmdiary:${DOCKER_HUB_TAG}
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - ALLOWED_URLS=${ALLOWED_URLS}
    restart: unless-stopped
    depends_on:
      - redis
      - db
volumes:
  fd_postgres_data:
  fd_redis_data:
  fd_static_volume:
  fd_web_media:
